name: Full CI. Pro/Plus version

on:
  push:
    branches:
    - master

env:
  DOCKER_ACTIONS_PROPLUS: |
    echo "FROM gableroux/unity3d:$UNITY_VERSION" > Dockerfile
    echo "COPY $DOCKER_ENTRYPOINT /entrypoint.sh" >> Dockerfile
    echo "COPY $PROJECT_PATH /$PROJECT_PATH" >> Dockerfile
    echo "RUN chmod +x /entrypoint.sh" >> Dockerfile
    echo "ENTRYPOINT [\"/entrypoint.sh\"]" >> Dockerfile
    docker build --tag $IMAGE_TAG ./
    docker run -i -w /$PROJECT_PATH/ \
      -e "UNITY_USERNAME=$UNITY_LOGIN" \
      -e "UNITY_PASSWORD=$UNITY_PASS" \
      -e "UNITY_SERIAL=$UNITY_KEY" \
      -e "PROJECT_PATH=$PROJECT_PATH" \
      -e "TEST_PLATFORM=$TEST_PLATFORM" \
      -e "WORKDIR=/$PROJECT_PATH/" \
      -v "$(pwd):/$PROJECT_PATH/" \
      $IMAGE_TAG \
      bash

jobs:
  TestsProPlus:
    name: Tests Pro/Plus
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - TestProject
        targetPlatform: [editmode, playmode]
        unityVersion: [2019.4.0f1, 2019.4.1f1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.unityVersion }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      - name: Run Tests
        env:
          UNITY_VERSION: ${{ matrix.unityVersion }}
          UNITY_LOGIN: ${{ secrets.UNITY_LOGIN }}
          UNITY_PASS: ${{ secrets.UNITY_PASS }}
          UNITY_KEY: ${{ secrets.UNITY_KEY }}
          DOCKER_ENTRYPOINT: ./.github/actions/unity/run-tests/entrypoint-proplus.sh
          PROJECT_PATH: ${{ matrix.projectPath }}
          TEST_PLATFORM: ${{ matrix.targetPlatform }}
          IMAGE_TAG: docker_image
        run: |
          eval "$DOCKER_ACTIONS_PROPLUS"
      - name: Upload results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ${{ matrix.unityVersion }}-${{ matrix.targetPlatform }}-tests-results
          path: ${{ matrix.targetPlatform }}-results.xml
